apiVersion: v1
kind: Namespace
metadata:
  name: topix
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: topix-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ~/script_files/topix_test
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: topix-data-pvc
  namespace: topix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: topix-data-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topix-deployment
  namespace: topix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topix
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: topix
    spec:
      containers:
      - name: topix
        image: vova0911/topix:amd64_latest
        ports:
        - containerPort: 5000
        # Uncomment if needed
        # imagePullSecrets:
        # - name: regcred
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: data-volume
          mountPath: ~/script_files/topix
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-config-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: topix-service
  namespace: topix
spec:
  selector:
    app: topix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30084
  type: NodePort

