apiVersion: v1
kind: Namespace
metadata:
  name: otacd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: otacd-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/script_files
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otacd-data-pvc
  namespace: otacd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: otacd-data-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: otacd-mongo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/script_files/otacd/mongo
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otacd-mongo-pvc
  namespace: otacd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: otacd-mongo-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: otacd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: "otacd"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: otacd-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: otacd
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otacd-deployment
  namespace: otacd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otacd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: otacd
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: otacd
          image: 192.168.68.64:5000/otacd:amd64_0.0.23
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_SECRET_KEY
              value: "change-me-in-prod"
            - name: MONGO_URL
              value: "mongodb://mongodb-service.otacd.svc.cluster.local:27017"
            - name: MONGO_DB_NAME
              value: "otacd"
            - name: VERSION
              value: "dev"
            - name: BRANCH
              value: "local"
            - name: IP
              value: "0.0.0.0"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          volumeMounts:
            - name: data-volume
              mountPath: /root/script_files
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: otacd-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: otacd-service
  namespace: otacd
spec:
  selector:
    app: otacd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30096
  type: NodePort

