apiVersion: v1
kind: ConfigMap
metadata:
  name: green-config
  namespace: default
data:
  BG_COLOR: "green"
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-config
  namespace: default
data:
  BG_COLOR: "blue"
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vbank-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vbank
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vbank
    spec:
      containers:
      - name: vbank
        image: vova0911/v_bank:amd64_latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: blue-config
   #   imagePullSecrets:
    #  - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: vbank-service
  namespace: default
spec:
  selector:
    app: vbank
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080  # This will bind to this port on your Node
  type: NodePort
---

