apiVersion: v1
kind: Namespace
metadata:
  name: weprintcloud
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: weprintcloud-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/script_files/weprintcloud_pg
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weprintcloud-postgres-pvc
  namespace: weprintcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: weprintcloud-postgres-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: weprintcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_DB
            value: "appdb"
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: weprintcloud-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: weprintcloud
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

