apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default  # Or specify your custom project
  source:
    repoURL: https://github.com/V0vaG/helm_test
    targetRevision: main  # The branch or tag
    path: apps  # Directory containing the child app manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/V0vaG/helm_test
    targetRevision: main
    path: jellyfin/jellyfin  # Directory containing the Kubernetes manifests for app1
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
