apiVersion: v1
kind: Service
metadata:
  name: {{ include "artifactory.fullname" . }}-artifactory
  labels:
  {{- include "artifactory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.artifactory.type }}
  selector:
    app: artifactory
    {{- include "artifactory.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.artifactory.ports | toYaml | nindent 2 }}