apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifactory.fullname" . }}-master-key
  labels:
  {{- include "artifactory.labels" . | nindent 4 }}
stringData:
  master.key: {{ required "masterKey.masterKey is required" .Values.masterKey.masterKey
    | quote }}
type: Opaque