apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.fullname" . }}-db-pvc
  labels:
  {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.dbPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.dbPvc.storageClass | quote }}
  volumeName: nextcloud-db-pv