apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-db
  labels:
  {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.type }}
  selector:
    app: nextcloud-db
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.db.ports | toYaml | nindent 2 }}