apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.fullname" . }}-files-pvc
  labels:
  {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.filesPvc.storageRequest | quote }}
  volumeName: nextcloud-files-pv