apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nextcloud.fullname" . }}-files-pv
  labels:
  {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /media/vova/2TB/nextcloud/files
  persistentVolumeReclaimPolicy: Retain