apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nextcloud.fullname" . }}-html-pv
  labels:
  {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/vova/script_files/nextcloud/html
  persistentVolumeReclaimPolicy: Retain