apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.fullname" . }}-html-pvc
  labels:
  {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.htmlPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.htmlPvc.storageClass | quote }}
  volumeName: nextcloud-html-pv