apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-service
  labels:
  {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nextcloud-app
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}