apiVersion: v1
kind: Service
metadata:
  name: {{ include "vovarepo.fullname" . }}-service
  labels:
  {{- include "vovarepo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: vovarepo
    {{- include "vovarepo.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}