deployment:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  vhub:
    image:
      repository: vova0911/vhub
      tag: amd64_1.0.6
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
  tools:
    image:
      tag: amd64_1.0.6
kubernetesClusterDomain: cluster.local
pvc:
  dataPvc:
    storageClass: ""
    storageRequest: 1Gi
service:
  ports:
    - nodePort: 30087
      port: 80
      protocol: TCP
      targetPort: 5000
  type: NodePort
