apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaniko-job-manager
  namespace: argocd
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete", "update"]

