apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaniko-job-manager-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argocd
roleRef:
  kind: Role
  name: kaniko-job-manager
  apiGroup: rbac.authorization.k8s.io

