deployment:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  vhide:
    image:
      repository: vova0911/vhide
      tag: amd64_1.1.1
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
kubernetesClusterDomain: cluster.local
pvc:
  dataPvc:
    storageClass: ""
    storageRequest: 1Gi
service:
  ports:
    - nodePort: 30095
      port: 80
      protocol: TCP
      targetPort: 5000
  type: NodePort
