apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql.fullname" . }}-postgres
  labels:
  {{- include "postgresql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: postgres
    {{- include "postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: postgres
      {{- include "postgresql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: {{ quote .Values.postgres.postgres.env.postgresUser }}
        - name: POSTGRES_PASSWORD
          value: {{ quote .Values.postgres.postgres.env.postgresPassword }}
        - name: POSTGRES_DB
          value: {{ quote .Values.postgres.postgres.env.postgresDb }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.postgres.postgres.image.repository }}:{{ .Values.postgres.postgres.image.tag
          | default .Chart.AppVersion }}
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      initContainers:
      - command:
        - sh
        - -c
        - "echo \"\U0001F527 Patching PV to clear claimRef...\"\nkubectl patch pv weprintcloud-postgres-pv
          -p '{\"spec\":{\"claimRef\": null}}' || true\n"
        env:
        - name: KUBECONFIG
          value: {{ quote .Values.postgres.unbindPv.env.kubeconfig }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.postgres.unbindPv.image.repository }}:{{ .Values.postgres.unbindPv.image.tag
          | default .Chart.AppVersion }}
        name: unbind-pv
        resources: {}
        volumeMounts:
        - mountPath: /root/.kube
          name: kubeconfig
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ include "postgresql.fullname" . }}-weprintcloud-postgres-pvc
      - hostPath:
          path: /root/.kube
          type: Directory
        name: kubeconfig