apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgresql.fullname" . }}-pv
  labels:
  {{- include "postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/vova/script_files/weprintcloud_pg
  storageClassName: ""