apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.fullname" . }}-pvc
  labels:
  {{- include "postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.pvc.storageClass | quote }}
  volumeName: postgres-pv