apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.fullname" . }}-ql-weprintcloud-postgres-pvc
  labels:
  {{- include "postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.qlWeprintcloudPostgresPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.qlWeprintcloudPostgresPvc.storageClass | quote
    }}
  volumeName: weprintcloud-postgres-pv