apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgresql.fullname" . }}-weprintcloud-postgres-pv
  labels:
    app: weprintcloud-postgres
  {{- include "postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/vova/script_files/weprintcloud_pg
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""