apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.fullname" . }}-weprintcloud-postgres-pvc
  labels:
  {{- include "postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.weprintcloudPostgresPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.weprintcloudPostgresPvc.storageClass | quote }}
  volumeName: weprintcloud-postgres-pv