apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab.fullname" . }}-gitlab
  labels:
  {{- include "gitlab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gitlab.replicas }}
  selector:
    matchLabels:
      app: gitlab
    {{- include "gitlab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: gitlab
      {{- include "gitlab.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: {{ quote .Values.gitlab.gitlab.env.gitlabOmnibusConfig }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.gitlab.gitlab.image.repository }}:{{ .Values.gitlab.gitlab.image.tag
          | default .Chart.AppVersion }}
        name: gitlab
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/gitlab
          name: config
        - mountPath: /var/log/gitlab
          name: logs
        - mountPath: /var/opt/gitlab
          name: data
      volumes:
      - hostPath:
          path: /home/vova/script_files/gitlab/config
          type: DirectoryOrCreate
        name: config
      - hostPath:
          path: /home/vova/script_files/gitlab/logs
          type: DirectoryOrCreate
        name: logs
      - hostPath:
          path: /home/vova/script_files/gitlab/data
          type: DirectoryOrCreate
        name: data