apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "gitlab.fullname" . }}-gitlab
  labels:
  {{- include "gitlab.labels" . | nindent 4 }}
spec:
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gitlab
    helm:
      values: |
        global:
          edition: ce
          hosts:
            domain: local
            https: false
            externalIP: ""
            gitlab:
              name: gitlab.local

        gitlab:
          webservice:
            service:
              type: NodePort
              nodePort: 30099

        root:
          password:
            secret: gitlab-root-secret
            key: password
    repoURL: https://charts.gitlab.io
    targetRevision: 7.11.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true