apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "list.fullname" . }}-data-pv
  labels:
  {{- include "list.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/vova/script_files/list
  storageClassName: ""