deployment:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  weather:
    image:
      repository: vova0911/weather
      tag: amd64_1.0.479
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
kubernetesClusterDomain: cluster.local
service:
  ports:
    - nodePort: 30081
      port: 80
      protocol: TCP
      targetPort: 5000
  type: NodePort
