apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vhub.fullname" . }}-kaniko-job-manager
  labels:
  {{- include "vhub.labels" . | nindent 4 }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - create
  - delete
  - update