apiVersion: v1
kind: Service
metadata:
  name: {{ include "vhub.fullname" . }}-vhub-service
  labels:
  {{- include "vhub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vhubService.type }}
  selector:
    app: vhub
    {{- include "vhub.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.vhubService.ports | toYaml | nindent 2 }}