apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vhub.fullname" . }}-vhub-data-pvc
  labels:
  {{- include "vhub.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.vhubDataPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.vhubDataPvc.storageClass | quote }}
  volumeName: vhub-data-pv