apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "jellyfin.fullname" . }}-cash-pv
  labels:
  {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/cache/jellyfin
  storageClassName: ""