apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "jellyfin.fullname" . }}-config-pv
  labels:
  {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /home/vova/16GB/jellyfin/config
  storageClassName: ""