apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "jellyfin.fullname" . }}-media-pv
  labels:
  {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /media/vova
  storageClassName: ""