apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "jellyfin.fullname" . }}-users-pv
  labels:
  {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/vova/jellyfin/users
  storageClassName: ""