apiVersion: v1
kind: Namespace
metadata:
  name: factory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: factory-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/script_files/factory
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factory-data-pvc
  namespace: factory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: factory-data-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory-deployment
  namespace: factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factory
  template:
    metadata:
      labels:
        app: factory
    spec:
      containers:
      - name: factory
        image: vova0911/factory:amd64_0.0.16
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - name: data-volume
          mountPath: /root/script_files/factory
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: factory-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: factory-service
  namespace: factory
spec:
  selector:
    app: factory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: factory-ingress
  namespace: factory
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /factory
        pathType: Prefix
        backend:
          service:
            name: factory-service
            port:
              number: 80
---
# Additional manifest for exposing Ingress Controller on port 95 via NodePort
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30095
    - name: http-alt
      port: 95
      targetPort: 80
      nodePort: 30096
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30097

