apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwix
  template:
    metadata:
      labels:
        app: kiwix
    spec:
      containers:
        - name: kiwix
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["/data/wikipedia_en_all_maxi.zim"]
          volumeMounts:
            - name: zim-data
              mountPath: {{ .Values.pvc.mountPath }}
          ports:
            - containerPort: 80
      volumes:
        - name: zim-data
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
