apiVersion: v1
kind: Service
metadata:
  name: {{ include "vbank.fullname" . }}-service
  labels:
  {{- include "vbank.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: vbank
    {{- include "vbank.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}