kubernetesClusterDomain: cluster.local
server:
  jellyfin:
    image:
      repository: jellyfin/jellyfin
      tag: latest
  replicas: 1
service:
  ports:
  - nodePort: 30080
    port: 8096
    protocol: TCP
    targetPort: 8096
  type: NodePort
