config:
  defaultConf: |-
    server {
        listen 80;
        server_name vova-g.tplinkdns.com;
        location /tools/ {
            rewrite ^/tools(/.*)$ $1 break;
            proxy_pass http://tools-service.tools.svc.cluster.local:80;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            sub_filter_once off;
            sub_filter_types text/html;
            sub_filter '<head>' '<base href="/tools/"><head>';
        }
        location /healthz {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
customNginx:
  nginx:
    image:
      repository: nginx
      tag: alpine
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  replicas: 1
  type: ClusterIP
kubernetesClusterDomain: cluster.local
