config:
  defaultConf: |-
    server {
        listen 443 ssl;
        server_name vova-g.tplinkdns.com;
        ssl_certificate /etc/ssl/fullchain.pem;
        ssl_certificate_key /etc/ssl/privkey.pem;
        location / {
            proxy_pass http://tools-service.tools.svc.cluster.local:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
customNginx:
  nginx:
    image:
      repository: nginx
      tag: alpine
  ports:
  - nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 443
  replicas: 1
  type: NodePort
kubernetesClusterDomain: cluster.local
