apiVersion: v1
kind: Namespace
metadata:
  name: vvault
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vvault-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/script_files/vvault
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vvault-data-pvc
  namespace: vvault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: vvault-data-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vvault-deployment
  namespace: vvault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vvault
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vvault
    spec:
      containers:
      - name: vvault
        image: 192.168.68.64:5000/vvault:amd64_latest
        ports:
        - containerPort: 5000
        # Uncomment if needed
        # imagePullSecrets:
        # - name: regcred
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - name: data-volume
          mountPath: /root/script_files/vvault
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: vvault-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vvault-service
  namespace: vvault
spec:
  selector:
    app: vvault
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30096
  type: NodePort
