apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shinobi.fullname" . }}-config
  labels:
  {{- include "shinobi.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.config.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.config.storageClass | quote }}