apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "shinobi.fullname" . }}-custom-pv
  labels:
  {{- include "shinobi.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /media/vova/2TB/shinobi/shinobi-custom
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shinobi-local