apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "v3d.fullname" . }}-data-pv
  labels:
  {{- include "v3d.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/vova/script_files/v3d
  storageClassName: ""