apiVersion: v1
kind: Namespace
metadata:
  name: vpkg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpkg-deployment
  labels:
    app: vpkg
  namespace: vpkg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vpkg
  template:
    metadata:
      labels:
        app: vpkg
    spec:
      containers:
        - name: vpkg-container
          image: vova0911/vpkg:amd64_latest
          ports:
            - containerPort: 5000
          env:
            - name: ENV_VAR
              value: "value"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: vpkg-service
  namespace: vpkg
spec:
  selector:
    app: vpkg
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpkg-ingress
  namespace: vpkg
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vpkg-service
                port:
                  number: 81
