apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"weather","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"weather","app.kubernetes.io/version":"0.1.0","helm.sh/chart":"weather-0.1.0"},"name":"weather-deployment","namespace":"weather"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"weather","app.kubernetes.io/instance":"weather","app.kubernetes.io/name":"weather"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"weather","app.kubernetes.io/instance":"weather","app.kubernetes.io/name":"weather"}},"spec":{"containers":[{"env":[{"name":"KUBERNETES_CLUSTER_DOMAIN","value":"cluster.local"}],"envFrom":[{"configMapRef":{"name":"weather-blue-config"}}],"image":"vova0911/weather:amd64_latest","name":"weather","ports":[{"containerPort":5000}],"resources":{}}]}}}}
    creationTimestamp: "2025-02-07T08:41:34Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: weather
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: weather
      app.kubernetes.io/version: 0.1.0
      helm.sh/chart: weather-0.1.0
    name: weather-deployment
    namespace: weather
    resourceVersion: "2299"
    uid: d890da40-a4ae-41fc-a925-a7625977c17d
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: weather
        app.kubernetes.io/instance: weather
        app.kubernetes.io/name: weather
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: weather
          app.kubernetes.io/instance: weather
          app.kubernetes.io/name: weather
      spec:
        containers:
        - env:
          - name: KUBERNETES_CLUSTER_DOMAIN
            value: cluster.local
          envFrom:
          - configMapRef:
              name: weather-blue-config
          image: vova0911/weather:amd64_latest
          imagePullPolicy: IfNotPresent
          name: weather
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-02-07T08:41:34Z"
      lastUpdateTime: "2025-02-07T08:41:34Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-02-07T08:41:34Z"
      lastUpdateTime: "2025-02-07T08:41:44Z"
      message: ReplicaSet "weather-deployment-5656ffcbcc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
