apiVersion: v1
kind: Service
metadata:
  name: {{ include "frigate.fullname" . }}-frigate
  labels:
  {{- include "frigate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frigate.type }}
  selector:
    app: frigate
    {{- include "frigate.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.frigate.ports | toYaml | nindent 2 }}