apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.fullname" . }}-service
  labels:
    app: jellyfin
  {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jellyfin
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}