apiVersion: v1
kind: Namespace
metadata:
  name: APP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP-deployment
  namespace: APP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: APP
    spec:
      containers:
      - name: APP
        image: vova0911/APP:amd64_latest
        ports:
        - containerPort: 5000
        # Uncomment if needed
        # imagePullSecrets:
        # - name: regcred
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: APP-service
  namespace: APP
spec:
  selector:
    app: APP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: PORT
  type: NodePort

