apiVersion: v1
kind: Service
metadata:
  name: {{ include "vhide.fullname" . }}-service
  labels:
  {{- include "vhide.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: vhide
    {{- include "vhide.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}