apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vpkg.fullname" . }}-vpkg-ingress
  labels:
  {{- include "vpkg.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "vpkg.fullname" . }}-webapp-service'
            port:
              number: 81
        path: /
        pathType: Prefix