apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}-custom-nginx
  labels:
  {{- include "nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.customNginx.replicas }}
  selector:
    matchLabels:
      app: custom-nginx
    {{- include "nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: custom-nginx
      {{- include "nginx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.customNginx.nginx.image.repository }}:{{ .Values.customNginx.nginx.image.tag
          | default .Chart.AppVersion }}
        name: nginx
        ports:
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf
        - mountPath: /etc/nginx/ssl
          name: nginx-tls
          readOnly: true
      volumes:
      - configMap:
          name: {{ include "nginx.fullname" . }}-config
        name: nginx-conf
      - name: nginx-tls
        secret:
          secretName: custom-nginx-tls