apiVersion: v1
kind: Namespace
metadata:
  name: vvolt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: vvolt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: vvolt
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
# PersistentVolume definition (if needed)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vvolt-data-pv
  namespace: vvolt
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/script_files/vvolt  # adjust accordingly
  storageClassName: ""
---
# PersistentVolumeClaim definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vvolt-data-pvc
  namespace: vvolt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: vvolt-data-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vvolt-deployment
  namespace: vvolt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vvolt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vvolt
    spec:
      containers:
      - name: vvolt
        image: vova0911/vvolt:amd64_0.2.2
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: mongodb://mongodb-service.vvolt.svc.cluster.local:27017
        volumeMounts:
        - name: data-volume
          mountPath: /root/script_files/vvolt
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: vvolt-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vvolt-service
  namespace: vvolt
spec:
  selector:
    app: vvolt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30088
  type: NodePort

