apiVersion: v1
kind: Namespace
metadata:
  name: vvolt
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vvolt-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/script_files/vvolt
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vvolt-data-pvc
  namespace: vvolt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: vvolt-data-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vvolt-deployment
  namespace: vvolt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vvolt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vvolt
    spec:
      containers:
      - name: vvolt
        image: vova0911/vvolt:amd64_0.2.3
        ports:
        - containerPort: 5000
        # Uncomment if needed
        # imagePullSecrets:
        # - name: regcred
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - name: data-volume
          mountPath: /root/script_files/vvolt
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: vvolt-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vvolt-service
  namespace: vvolt
spec:
  selector:
    app: vvolt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30088
  type: NodePort
