apiVersion: v1
kind: Namespace
metadata:
  name: gitlab

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:16.11.1-ce.0
          ports:
            - containerPort: 80
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://gitlab.local'
          volumeMounts:
            - name: config
              mountPath: /etc/gitlab
            - name: logs
              mountPath: /var/log/gitlab
            - name: data
              mountPath: /var/opt/gitlab
      volumes:
        - name: config
          hostPath:
            path: /home/vova/script_files/gitlab/config
            type: DirectoryOrCreate
        - name: logs
          hostPath:
            path: /home/vova/script_files/gitlab/logs
            type: DirectoryOrCreate
        - name: data
          hostPath:
            path: /home/vova/script_files/gitlab/data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30099

