apiVersion: v1
kind: Namespace
metadata:
  name: gitlab

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "gitlab.local"
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:16.11.1-ce.0
          ports:
            - containerPort: 80
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://gitlab.local'
            - name: GITLAB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitlab-root-secret
                  key: password
          volumeMounts:
            - name: config
              mountPath: /etc/gitlab
            - name: logs
              mountPath: /var/log/gitlab
            - name: data
              mountPath: /var/opt/gitlab
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 10
      volumes:
        - name: config
          hostPath:
            path: /home/vova/script_files/gitlab/config
            type: DirectoryOrCreate
        - name: logs
          hostPath:
            path: /home/vova/script_files/gitlab/logs
            type: DirectoryOrCreate
        - name: data
          hostPath:
            path: /home/vova/script_files/gitlab/data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-root-secret
  namespace: gitlab
type: Opaque
data:
  password: c3VwZXJfc2VjdXJlX3Jvb3QK  # base64 for "super_secure_root"

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30099

