kubernetesClusterDomain: cluster.local
postgres:
  postgres:
    env:
      postgresDb: appdb
      postgresPassword: password
      postgresUser: postgres
    image:
      repository: postgres
      tag: "14"
  replicas: 1
  unbindPv:
    env:
      kubeconfig: /root/.kube/config
    image:
      repository: bitnami/kubectl
      tag: latest
postgresService:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
pvc:
  weprintcloudPostgresPvc:
    storageClass: ""
    storageRequest: 1Gi
