kubernetesClusterDomain: cluster.local
mongodb:
  mongodb:
    image:
      repository: mongo
      tag: "5"
  replicas: 1
mongodbService:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  type: ClusterIP
vvoltDeployment:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  vvolt:
    env:
      mongoUrl: mongodb://mongodb-service.vvolt.svc.cluster.local:27017
    image:
      repository: vova0911/vvolt
      tag: amd64_0.2.2
vvoltService:
  ports:
  - nodePort: 30088
    port: 80
    protocol: TCP
    targetPort: 5000
  type: NodePort
