apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "vovastl.fullname" . }}-data-pv
  labels:
  {{- include "vovastl.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/vova/script_files/vovastl
  storageClassName: ""