{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "vovastl.fullname" . }}-stripprefix
  labels:
    {{- include "vovastl.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /vovastl
{{- end }}

