apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}-service
  labels:
  {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mongodb
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}