apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factory.fullname" . }}-factory-deployment
  labels:
  {{- include "factory.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.factoryDeployment.replicas }}
  selector:
    matchLabels:
      app: factory
    {{- include "factory.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: factory
      {{- include "factory.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.factoryDeployment.factory.image.repository }}:{{ .Values.factoryDeployment.factory.image.tag
          | default .Chart.AppVersion }}
        name: factory
        ports:
        - containerPort: 5000
        resources: {{- toYaml .Values.factoryDeployment.factory.resources | nindent 10
          }}
        volumeMounts:
        - mountPath: /root/script_files/factory
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ include "factory.fullname" . }}-factory-data-pvc