apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factory.fullname" . }}-deployment
  labels:
  {{- include "factory.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge | quote }}
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
    type: {{ .Values.deployment.strategy.type | quote }}
  selector:
    matchLabels:
      app: factory
    {{- include "factory.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: factory
      {{- include "factory.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.deployment.factory.image.repository }}:{{ .Values.deployment.factory.image.tag
          | default .Chart.AppVersion }}
        name: factory
        ports:
        - containerPort: 5000
        resources: {}
        securityContext: {{- toYaml .Values.deployment.factory.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /root/script_files/factory
          name: data-volume
        - mountPath: /var/run/docker.sock
          name: docker-socket
        - mountPath: /usr/bin/docker
          name: docker-bin
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ include "factory.fullname" . }}-data-pvc
      - hostPath:
          path: /var/run/docker.sock
        name: docker-socket
      - hostPath:
          path: /usr/bin/docker
        name: docker-bin