apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "factory.fullname" . }}-factory-data-pvc
  labels:
  {{- include "factory.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.factoryDataPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.factoryDataPvc.storageClass | quote }}
  volumeName: factory-data-pv