apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "otacd.fullname" . }}-otacd-mongo-pv
  labels:
  {{- include "otacd.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/vova/script_files/otacd/mongo
  storageClassName: ""