apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "otacd.fullname" . }}-otacd-data-pvc
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
  {{- include "otacd.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.otacdDataPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.otacdDataPvc.storageClass | quote }}