apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "otacd.fullname" . }}-otacd-data-pv
  labels:
  {{- include "otacd.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/vova/script_files
  storageClassName: ""