apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
  labels:
    app: python-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      containers:
      - name: python-web-app
        image: vova0911/weather:latest
        ports:
        - containerPort: 80
        env:
        - name: ENV_VAR_EXAMPLE
          value: "production"
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
  labels:
    app: python-web-app
spec:
  selector:
    app: python-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-web-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-web-app-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-web-app-nodeport
spec:
  selector:
    app: python-web-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081  # Maps localhost:81 to container's port 80

