apiVersion: v1
kind: Namespace
metadata:
  name: custom-nginx

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-nginx-config
  namespace: custom-nginx
data:
  default.conf: |
    server {
        listen 443 ssl;
        server_name vova-g.tplinkdns.com;

        ssl_certificate /etc/ssl/fullchain.pem;
        ssl_certificate_key /etc/ssl/privkey.pem;

        location / {
            proxy_pass http://tools-service.tools.svc.cluster.local:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx
  namespace: custom-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: nginx-tls
          mountPath: /etc/ssl
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: custom-nginx-config
      - name: nginx-tls
        secret:
          secretName: custom-nginx-tls

---

apiVersion: v1
kind: Service
metadata:
  name: custom-nginx
  namespace: custom-nginx
spec:
  selector:
    app: custom-nginx
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
  type: NodePort
