apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lora.fullname" . }}-server
  labels:
    app: lora
  {{- include "lora.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: lora
    {{- include "lora.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: lora
      {{- include "lora.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.server.lora.image.repository }}:{{ .Values.server.lora.image.tag
          | default .Chart.AppVersion }}
        name: lora
        ports:
        - containerPort: 5000
        resources: {}