apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "lora.fullname" . }}-lora-app
  labels:
  {{- include "lora.labels" . | nindent 4 }}
spec:
  destination:
    namespace: lora-namespace
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lora/lora
    repoURL: https://github.com/V0vaG/helm_test
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true