apiVersion: v1
kind: Service
metadata:
  name: {{ include "lora.fullname" . }}-nginx-service
  labels:
  {{- include "lora.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginxService.type }}
  selector:
    app: nginx
    {{- include "lora.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.nginxService.ports | toYaml | nindent 2 }}