apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vvolt.fullname" . }}-mongodb
  labels:
  {{- include "vvolt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
    {{- include "vvolt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mongodb
      {{- include "vvolt.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mongodb.mongodb.image.repository }}:{{ .Values.mongodb.mongodb.image.tag
          | default .Chart.AppVersion }}
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: {{ include "vvolt.fullname" . }}-mongodb-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vvolt.fullname" . }}-vvolt-deployment
  labels:
  {{- include "vvolt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vvoltDeployment.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.vvoltDeployment.strategy.rollingUpdate.maxSurge | quote
        }}
      maxUnavailable: {{ .Values.vvoltDeployment.strategy.rollingUpdate.maxUnavailable
        }}
    type: {{ .Values.vvoltDeployment.strategy.type | quote }}
  selector:
    matchLabels:
      app: vvolt
    {{- include "vvolt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: vvolt
      {{- include "vvolt.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MONGO_URL
          value: {{ quote .Values.vvoltDeployment.vvolt.env.mongoUrl }}
        - name: MONGODB_ROOT_USER
          valueFrom:
            secretKeyRef:
              key: MONGODB_ROOT_USER
              name: mongodb-root-creds
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MONGODB_ROOT_PASSWORD
              name: mongodb-root-creds
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.vvoltDeployment.vvolt.image.repository }}:{{ .Values.vvoltDeployment.vvolt.image.tag
          | default .Chart.AppVersion }}
        name: vvolt
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /root/script_files/vvolt
          name: data-volume
        - mountPath: /etc/mongo-secret
          name: mongo-secret
          readOnly: true
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ include "vvolt.fullname" . }}-vvolt-data-pvc
      - name: mongo-secret
        secret:
          secretName: mongodb-root-creds