apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "vvolt.fullname" . }}-vvolt-data-pv
  labels:
  {{- include "vvolt.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/vova/script_files/vvolt
  storageClassName: ""