apiVersion: v1
kind: Service
metadata:
  name: {{ include "vvolt.fullname" . }}-vvolt-service
  labels:
  {{- include "vvolt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vvoltService.type }}
  selector:
    app: vvolt
    {{- include "vvolt.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.vvoltService.ports | toYaml | nindent 2 }}