apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vvolt.fullname" . }}-vvolt-data-pvc
  labels:
  {{- include "vvolt.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.vvoltDataPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.vvoltDataPvc.storageClass | quote }}
  volumeName: vvolt-data-pv