app:
  nextcloud:
    env:
      mysqlDatabase: nextcloud
      mysqlHost: nextcloud-db
      mysqlPassword: nextcloudpass
      mysqlUser: nextcloud
    image:
      repository: nextcloud
      tag: 28.0.4-apache
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
  replicas: 1
db:
  mariadb:
    env:
      mysqlDatabase: nextcloud
      mysqlPassword: nextcloudpass
      mysqlRootPassword: rootpass
      mysqlUser: nextcloud
    image:
      repository: mariadb
      tag: "10.6"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  ports:
  - port: 3306
    targetPort: 3306
  replicas: 1
  type: ClusterIP
kubernetesClusterDomain: cluster.local
pvc:
  dbPvc:
    storageClass: ""
    storageRequest: 5Gi
  filesPvc:
    storageClass: ""
    storageRequest: 10Gi
  htmlPvc:
    storageClass: ""
    storageRequest: 5Gi
service:
  ports:
  - nodePort: 30088
    port: 80
    targetPort: 80
  type: NodePort
