jellyfin:
  jellyfin:
    env:
      jellyfinPublishedservername: vova_server
    image:
      repository: jellyfin/jellyfin
      tag: latest
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
  replicas: 1
  type: ClusterIP
jellyfinProxy:
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
  type: ClusterIP
kubernetesClusterDomain: cluster.local
pvc:
  jellyfinConfigPvc:
    storageClass: ""
    storageRequest: 5Gi
  jellyfinMediaPvc:
    storageClass: ""
    storageRequest: 8000Gi
