jellyfin:
  jellyfin:
    env:
      jellyfinPublishedservername: vova_server
    image:
      repository: jellyfin/jellyfin
      tag: latest
  ports:
  - nodePort: 30080
    port: 8096
    protocol: TCP
    targetPort: 8096
  replicas: 1
  type: NodePort
kubernetesClusterDomain: cluster.local
pvc:
  cachePvc:
    storageClass: ""
    storageRequest: 5Gi
  configPvc:
    storageClass: ""
    storageRequest: 5Gi
  mediaPvc:
    storageClass: ""
    storageRequest: 50Gi
  webPvc:
    storageClass: ""
    storageRequest: 5Gi
