jellyfin:
  jellyfin:
    image:
      repository: jellyfin/jellyfin
      tag: latest
    resources:
      limits:
        nvidia.com/gpu: "1"
  ports:
  - nodePort: 30080
    port: 8096
    protocol: TCP
    targetPort: 8096
  replicas: 1
  type: NodePort
kubernetesClusterDomain: cluster.local
nvidiaDevicePluginDaemonset:
  nvidiaDevicePlugin:
    containerSecurityContext:
      allowPrivilegeEscalation: false
    env:
      failOnInitError: "false"
    image:
      repository: nvcr.io/nvidia/k8s-device-plugin
      tag: v0.13.0
pvc:
  jellyfinConfigPvc:
    storageClass: ""
    storageRequest: 5Gi
  jellyfinMediaPvc:
    storageClass: ""
    storageRequest: 50Gi
  jellyfinUsersPvc:
    storageClass: ""
    storageRequest: 5Gi
