deployment:
  factory:
    containerSecurityContext:
      privileged: true
    image:
      repository: vova0911/factory
      tag: amd64_1.0.9
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
kubernetesClusterDomain: cluster.local
pvc:
  dataPvc:
    storageClass: ""
    storageRequest: 1Gi
service:
  ports:
  - nodePort: 30087
    port: 80
    protocol: TCP
    targetPort: 5000
  type: NodePort
