deployment:
  factory:
    image:
      repository: vova0911/factory
      tag: amd64_0.0.16
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
pvc:
  dataPvc:
    storageClass: ""
    storageRequest: 1Gi
service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  type: ClusterIP
