factoryDeployment:
  factory:
    image:
      repository: vova0911/factory
      tag: amd64_0.0.16
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
factoryService:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  type: ClusterIP
ingressNginxController:
  ports:
  - name: http
    nodePort: 30095
    port: 80
    targetPort: 80
  - name: http-alt
    nodePort: 30096
    port: 95
    targetPort: 80
  - name: https
    nodePort: 30097
    port: 443
    targetPort: 443
  type: NodePort
kubernetesClusterDomain: cluster.local
pvc:
  factoryDataPvc:
    storageClass: ""
    storageRequest: 1Gi
