---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lora-server
  labels:
    app: lora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lora
  template:
    metadata:
      labels:
        app: lora
    spec:
      containers:
        - name: lora
          image: vova0911/lora:armhf_main
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: lora-service
  labels:
    app: lora
spec:
  type: NodePort
  selector:
    app: lora
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lora-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "vova-g.tplinkdns.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lora-service
                port:
                  number: 30080

