apiVersion: v1
kind: Namespace
metadata:
  name: vhub
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vhub-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/script_files/vhub
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vhub-data-pvc
  namespace: vhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: vhub-data-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vhub-deployment
  namespace: vhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vhub
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vhub
    spec:
      containers:
      - name: vhub
        image: vova0911/vhub:amd64_1.0.24
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
        volumeMounts:
        - name: data-volume
          mountPath: /root/script_files/vhub
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: docker-bin
          mountPath: /usr/bin/docker
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: vhub-data-pvc
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: docker-bin
        hostPath:
          path: /usr/bin/docker
---
apiVersion: v1
kind: Service
metadata:
  name: vhub-service
  namespace: vhub
spec:
  selector:
    app: vhub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30087
  type: NodePort
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaniko-job-manager
  namespace: vhub
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete", "update"]
