apiVersion: v1
kind: Namespace
metadata:
  name: vhub
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vhub-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/script_files/vhub
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vhub-data-pvc
  namespace: vhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: vhub-data-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vhub-deployment
  namespace: vhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vhub
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vhub
    spec:
      initContainers:
      - name: install-git
        image: debian:latest  # Change this based on your base image (e.g., ubuntu, alpine)
        command: ["/bin/sh", "-c", "apt-get update && apt-get install -y git"]
        volumeMounts:
        - name: git-bin
          mountPath: /usr/bin/git

      containers:
      - name: vhub
        image: vova0911/vhub:amd64_latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - name: data-volume
          mountPath: /root/script_files/vhub
        - name: git-bin
          mountPath: /usr/bin/git

      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: vhub-data-pvc
      - name: git-bin
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: vhub-service
  namespace: vhub
spec:
  selector:
    app: vhub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30087
  type: NodePort

