apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: topix
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: topix/topix
    repoURL: https://github.com/V0vaG/helm_test
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vbank
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: vbank/vbank
    repoURL: https://github.com/V0vaG/helm_test
    targetRevision: HEAD
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: vpkg
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     namespace: argocd
#     server: {{ .Values.spec.destination.server }}
#   project: default
#   source:
#     path: vpkg/vpkg
#     repoURL: https://github.com/V0vaG/helm_test
#     targetRevision: HEAD
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: weather
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     namespace: argocd
#     server: {{ .Values.spec.destination.server }}
#   project: default
#   source:
#     path: weather/weather
#     repoURL: https://github.com/V0vaG/helm_test
#     targetRevision: HEAD


---
apiVersion: argoproj.io/v1alpha1
kind: List
items:
{{- range .Values.apps }}
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: {{ .name }}
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: argocd
        server: {{ $.Values.spec.destination.server }}
      project: default
      source:
        path: {{ .path_value }}
        repoURL: https://github.com/V0vaG/helm_test
        targetRevision: {{ .branch }}
{{- end }}




# apps:
#   - name: weather
#     path_value: weather/weather
#     branch: main
#   # - name: vpkg
#   #   path_value: vpkg/vpkg
#   #   branch: main
