apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpkg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: vpkg/vpkg
    repoURL: https://github.com/V0vaG/helm_test
    targetRevision: HEAD
