gitlab:
  gitlab:
    env:
      gitlabOmnibusConfig: |
        external_url 'http://gitlab.local'
    image:
      repository: gitlab/gitlab-ce
      tag: 16.11.10
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - name: http
    nodePort: 30099
    port: 80
    targetPort: 80
  type: NodePort
