---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cash-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/cache/jellyfin
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-log-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/log/jellyfin
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-metadata-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/jellyfin/metadata
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/jellyfin/config
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-users-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/jellyfin/users
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/jellyfin/media
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cash-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: jellyfin-cash-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-log-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: jellyfin-log-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-metadata-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: jellyfin-metadata-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: jellyfin-config-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-users-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: jellyfin-users-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: jellyfin-media-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: cash-volume
          mountPath: /cash
        - name: log-volume
          mountPath: /config/log
        - name: metadata-volume
          mountPath: /config/metadata
        - name: config-volume
          mountPath: /config
        - name: users-volume
          mountPath: /data/users
        - name: media-volume
          mountPath: /data/media
      volumes:
      - name: cash-volume
        persistentVolumeClaim:
          claimName: jellyfin-cash-pvc
      - name: log-volume
        persistentVolumeClaim:
          claimName: jellyfin-log-pvc
      - name: metadata-volume
        persistentVolumeClaim:
          claimName: jellyfin-metadata-pvc
      - name: config-volume
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: users-volume
        persistentVolumeClaim:
          claimName: jellyfin-users-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: jellyfin-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
  - protocol: TCP
    port: 8096
    targetPort: 8096
    nodePort: 30080
  type: NodePort

