deployment:
  coldvaultmanagers:
    image:
      repository: 192.168.68.64:5000/coldvaultmanager
      tag: 1.0.16
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  coldvaultmanager:
    image:
      tag: amd64_0.1.2
kubernetesClusterDomain: cluster.local
pvc:
  dataPvc:
    storageClass: ""
    storageRequest: 1Gi
service:
  ports:
    - nodePort: 30091
      port: 80
      protocol: TCP
      targetPort: 5000
  type: NodePort
