deployment:
  minihub:
    image:
      repository: 192.168.68.64:5000/minihub
      tag: amd64_0.0.6
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
kubernetesClusterDomain: cluster.local
pvc:
  dataPvc:
    storageClass: ""
    storageRequest: 1Gi
service:
  ports:
    - nodePort: 30093
      port: 80
      protocol: TCP
      targetPort: 5000
  type: NodePort
