apiVersion: v1
kind: Namespace
metadata:
  name: vbank

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vbank-deployment
  namespace: vbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vbank
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vbank
    spec:
      containers:
      - name: vbank
        image: vova0911/v_bank:amd64_latest
        ports:
        - containerPort: 5000
        # Uncomment if needed
        # imagePullSecrets:
        # - name: regcred
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: vbank-service
  namespace: vbank
spec:
  selector:
    app: vbank
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30082
  type: NodePort

