deployment:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  v3D:
    image:
      repository: vova0911/v3d
      tag: amd64_latest
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
  v3d:
    image:
      tag: |
        amd64_0.0.1
kubernetesClusterDomain: cluster.local
pvc:
  dataPvc:
    storageClass: ""
    storageRequest: 1Gi
service:
  ports:
    - nodePort: 30089
      port: 80
      protocol: TCP
      targetPort: 5000
  type: NodePort
