apiVersion: v1
kind: Namespace
metadata:
  name: frigate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: frigate-local
  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /media/vova/2TB/frigate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-pvc
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: frigate-local
  resources:
    requests:
      storage: 1Ti

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
spec:
  replicas: 1

  selector:
    matchLabels:
      app: frigate

  template:
    metadata:
      labels:
        app: frigate

    spec:
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:stable

          securityContext:
            privileged: true

          ports:
            - name: web
              containerPort: 5000
            - name: rtsp
              containerPort: 8554
            - name: webrtc-tcp
              containerPort: 8555
              protocol: TCP
            - name: webrtc-udp
              containerPort: 8555
              protocol: UDP

          env:
            - name: TZ
              value: Asia/Jerusalem

          volumeMounts:
            - name: frigate-storage
              mountPath: /media/frigate

            - name: frigate-config
              mountPath: /config

            - name: shm
              mountPath: /dev/shm

          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "4"
              memory: "6Gi"

      volumes:
        - name: frigate-storage
          persistentVolumeClaim:
            claimName: frigate-pvc

        - name: frigate-config
          hostPath:
            path: /media/vova/2TB/frigate/config
            type: DirectoryOrCreate

        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: frigate
spec:
  type: NodePort
  selector:
    app: frigate
  ports:
    - name: web
      port: 5000
      targetPort: 5000
      nodePort: 30500

    - name: rtsp
      port: 8554
      targetPort: 8554
      nodePort: 31554

    - name: webrtc
      port: 8555
      targetPort: 8555
      nodePort: 31555