apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "kiwix.fullname" . }}-zim-pv
  labels:
  {{- include "kiwix.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 120Gi
  hostPath:
    path: /home/vova/Downloads