apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kiwix.fullname" . }}-zim-pvc
  labels:
  {{- include "kiwix.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.zimPvc.storageRequest | quote }}