apiVersion: v1
kind: PersistentVolume
metadata:
  name: kiwix-zim-pv
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 120Gi
  hostPath:
    path: /opt/kiwix
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-zim-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwix
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwix
  template:
    metadata:
      labels:
        app: kiwix
    spec:
      containers:
        - name: kiwix
          image: ghcr.io/kiwix/kiwix-serve:latest
          args: ["/data/wikipedia_he_all_nopic_2024-06.zim"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: zim-volume
              mountPath: /data
              readOnly: true
      volumes:
        - name: zim-volume
          persistentVolumeClaim:
            claimName: kiwix-zim-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kiwix-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: kiwix
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30098

