apiVersion: v1
kind: Namespace
metadata:
  name: vpkg

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpkg-deployment
  namespace: vpkg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpkg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vpkg
    spec:
      containers:
      - name: vpkg
        image: vova0911/vpkg:amd64_latest
        ports:
        - containerPort: 5000
        # Uncomment if needed
        # imagePullSecrets:
        # - name: regcred
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: vpkg-service
  namespace: vpkg
spec:
  selector:
    app: vpkg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30083
  type: NodePort

