apiVersion: v1
kind: Namespace
metadata:
  name: vovastl
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vovastl-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/script_files/vovastl
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vovastl-data-pvc
  namespace: vovastl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: vovastl-data-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vovastl-deployment
  namespace: vovastl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vovastl
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vovastl
    spec:
      containers:
      - name: vovastl
        image: vova0911/vovastl:amd64_1.1.11
        ports:
        - containerPort: 5000
        # Uncomment if needed
        # imagePullSecrets:
        # - name: regcred
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - name: data-volume
          mountPath: /root/script_files/vovastl
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: vovastl-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vovastl-service
  namespace: vovastl
spec:
  selector:
    app: vovastl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30089
  type: NodePort

