kubernetesClusterDomain: cluster.local
server:
  lora:
    image:
      repository: vova0911/lora
      tag: armhf_main
  replicas: 1
service:
  ports:
  - nodePort: 30080
    port: 5000
    protocol: TCP
    targetPort: 5000
  type: NodePort
