apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather.fullname" . }}-service
  labels:
  {{- include "weather.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: weather
    {{- include "weather.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}