apiVersion: v1
kind: Namespace
metadata:
  name: tools

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools-deployment
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
      - name: tools
        image: vova0911/tools:amd64_latest
        ports:
        - containerPort: 5000
        # Uncomment if needed
        # imagePullSecrets:
        # - name: regcred
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: tools-service
  namespace: tools
spec:
  selector:
    app: tools
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30085
  type: NodePort

