apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "vova-stl.fullname" . }}-data-pv
  labels:
  {{- include "vova-stl.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/vova/script_files/vova-stl
  storageClassName: ""