apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "topix.fullname" . }}-data-pv
  labels:
  {{- include "topix.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: ~/script_files/topix
  storageClassName: ""
