apiVersion: v1
kind: Service
metadata:
  name: {{ include "topix.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "topix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}
