apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "topix.fullname" . }}-data-pvc
  labels:
  {{- include "topix.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.dataPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.dataPvc.storageClass | quote }}
  volumeName: topix-data-pv