apiVersion: v1
kind: Namespace
metadata:
  name: v3d
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: v3d-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/vova/script_files/v3d
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v3d-data-pvc
  namespace: v3d
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: v3d-data-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v3d-deployment
  namespace: v3d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v3d
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: v3d
    spec:
      containers:
      - name: v3d
        image: vova0911/v3d:amd64_latest
        ports:
        - containerPort: 5000
        # Uncomment if needed
        # imagePullSecrets:
        # - name: regcred
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - name: data-volume
          mountPath: /root/script_files/v3d
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: v3d-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: v3d-service
  namespace: v3d
spec:
  selector:
    app: v3d
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30089
  type: NodePort

